Open MailKit secure socket option setting
serilog/serilog-sinks-email pull request #87
Opened 2020-10-20 02:48 UTC by arthurchiakh

related to Issue #69 

Enable user to set secure socket option for MailKit

2020-11-06 02:59 UTC, arthurchiakh commented
Hi, @nblumhardt ,
do you mind checking this PR? 
This change is to let user to specify secure socket option setting for MailKit, which can increase the range of supported email servers for this library.
In my case, I can only connect to Office365 email server when the secure socket option set to SecureSocketOptions.StartTls.
Please see also related issue #69 **Mailkit client use SecureSocketOptions** .

2020-11-13 15:51 UTC, Gondost commented
I would like to see this merged as well, I need to set the SecureSocketOptions in order to send email in my environment.

2020-11-13 23:14 UTC, nblumhardt commented
Thanks for the nudge. I would prefer not to expose `MailKit` types directly on the email sink's API - is there a higher-level way this can be expressed, akin to how we currently set `EnableSSL`?

2020-11-16 17:54 UTC, Gondost commented
@nblumhardt 

`EnableSSL` is a bit simpler because it's a boolean on both ends, whereas `SecureSocketOptions` is an enum. At some point, the enum will have to be validated to ascertain whether it's valid. This seems to lead to paths like creating your own enum with the same values as `SecureSocketOptions`, etc. Or, casting it in some manner and doing an automatic mapping. One way or the other, enum/type mapping seems unavoidable, so it seems like it's a matter of how you prefer to structure the sink code.

2021-05-24 15:40 UTC, andriysavin commented
> Thanks for the nudge. I would prefer not to expose `MailKit` types directly on the email sink's API - is there a higher-level way this can be expressed, akin to how we currently set `EnableSSL`?

I think this sink should introduce an enum similar or the same to SecureSocketOptions to avoid dependency on MailKit. And have one-to-one mapping between these enums. Come on, guys, lets finish this, it will be very useful!

2021-05-24 22:26 UTC, nblumhardt commented
Introducing an enum that maps to MailKit's one sounds reasonable 👍

2021-05-25 15:14 UTC, arthurchiakh commented
I'm sorry guys, better late than never.
I have added a dedicated Enum to map the MailKit socket options.

@nblumhardt please review my latest change. Thanks loads.

2021-05-25 17:31 UTC, andriysavin commented on src/Serilog.Sinks.Email/Sinks/Email/MailKitSecureSocketOptions.cs
> +namespace Serilog.Sinks.Email.Sinks.Email
Duplicate in the namespace

2021-05-25 17:33 UTC, andriysavin commented on src/Serilog.Sinks.Email/Sinks/Email/MailKitSecureSocketOptions.cs
> +        //
Could you wrap the docs in xml tags so they are shown by intellisense?

2021-05-25 17:35 UTC, andriysavin commented on src/Serilog.Sinks.Email/Sinks/Email/MailKitSecureSocketOptions.cs
> +{
I believe the goal of adding this enum was to hide dependency on MailKit. So maybe it should be named just "SecureSocketOptions"?

2021-05-26 01:54 UTC, arthurchiakh commented
@nblumhardt  @andriysavin 
I already changed the code accordingly. 
Please let me know anything that I can improve. 
Thanks.

2021-05-26 07:56 UTC, andriysavin approved these changes

2021-05-28 05:04 UTC, arthurchiakh commented
@nblumhardt Hi,
can you have a look on this?

2021-06-03 18:58 UTC, andriysavin commented
@nblumhardt please, take a look

2021-06-04 04:36 UTC, nblumhardt requested changes
Looking good 👍

2021-06-04 04:36 UTC, nblumhardt commented on src/Serilog.Sinks.Email/Sinks/Email/SecureSocketOptions.cs
> +﻿#if MAIL_KIT
This file should attribute the original source in MailKit (including its license header or link to the MailKit license).

2021-06-04 04:36 UTC, nblumhardt commented on src/Serilog.Sinks.Email/Sinks/Email/SecureSocketOptions.cs
> +        /// Allow the MailKit.IMailService to decide which SSL or TLS options to use (default).
> Allow the implementation to decide ...

?

2021-06-04 04:36 UTC, nblumhardt commented on src/Serilog.Sinks.Email/Sinks/Email/SecureSocketOptions.cs
> +        /// then the connection will fail and a System.NotSupportedException will be thrown.
The exception won't propagate out of Serilog, here, so `and a System.NotSupportedException will be thrown.` can probably just be trimmed off.

2021-06-04 21:40 UTC, nblumhardt commented
Righto! 👍 Let's give this a try on `dev` 😎

2021-06-04 21:40 UTC, merged

2021-06-05 06:58 UTC, andriysavin commented
@nblumhardt Is there a package feed for dev branch?

2021-06-05 12:01 UTC, arthurchiakh commented
> @nblumhardt Is there a package feed for dev branch?

I believe this is the one.
https://www.nuget.org/packages/Serilog.Sinks.Email/2.4.1-dev-00128

2021-06-26 10:34 UTC, lenlenya commented
Thank you for your contribution, It's very helpful to me.